[package]
name = "zek-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "CLI de zek: workflow orchestrator"

[[bin]]
name = "zek"
path = "src/main.rs"

[dependencies]
zek-core = { path = "../zek-core", version = "0.1.0" }
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
dialoguer = "0.11"
anyhow = "1"
colored = "2"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
